name = "Prototype of camera casting"
uid = "fa-prototype-camera-casting"
icon = "/mods/fa-casting-cinematics/icon.png"
version = 1
description = "A prototype to give casters a more natural control over the camera when they are in split screen."
author = "Jip"
license = "MIT"
exclusive = false
ui_only = true
